### PR TITLE
feat: Add Compliance client

### PR DESCRIPTION
**Pull request by AsToNlele**
[RHINENG-9009](https://issues.redhat.com/browse/RHINENG-9009)

This will be a new package, let me know if anything is missing.

### CODE REVIEW

**Comment by AsToNlele** [comment]
Is there any automation present when the api spec changes?

**Comment by Hyperkid123** [comment]
We are currently migrating to a new repository management tool. This one is missing some configurations. @apinkert can you update this PR with the missing bits?

**Comment by apinkert** [comment]
@Hyperkid123 added the project config files. @AsToNlele apologies, we're still in the process of updating docs to match the new build infrastructure. I've pushed a commit that adds the missing config files for your client

**Comment by AsToNlele** [comment]
Hi thanks for your input, could you please have a look again? @apinkert
Can't figure out why it's not building

**Comment by Hyperkid123** [comment]
@AsToNlele the PR needs to be rebased. It should also be onboarded to the new generator, rather than using the old one. You would have migrate anyways.

**Pull request closed without merging**
