### PR TITLE
Add new insights client

### PR DESCRIPTION
**Pull request by karelhala**
* Add insights API @AllenBW
* Updates to newest API - vulnerabilitye @jiridostal, topological inventory, sources and catalog @Hyperkid123

### CODE REVIEW

**Comment by karelhala** [comment]
This should not take effect on anyone already using any API if they are using fixed version otherwise everybody will get newest version of these APIs.

**Comment by AllenBW** [comment]
👍 
cc @dkuc

**Comment by jiridostal** [comment]
Should be no problem for Vulnerability :+1:

**Pull request merged**
