### PR TITLE
RHCLOUD-32394: Update axios to latest for able clients

### PR DESCRIPTION
**Pull request by florkbr**
See https://issues.redhat.com/browse/RHCLOUD-32394

### CODE REVIEW

**Review by Hyperkid123 — CHANGES_REQUESTED** [review]
We can't bump them all. Only those clients using the v2 can be bumped. Axios v1 introduces breaking changes. Thats why the tasks is connected to the new generators.

**Comment by florkbr** [comment]
@Hyperkid123 ah - alright. Thanks for clarifying. I did notice I needed to update the axios version in `packages/shared` (otherwise typescript complains the parameters passed into axios in the upgraded clients are invalid). Is that going to cause an issue for the older clients on the old generator?

**Comment by Hyperkid123** [comment]
The shared package is not used in the old clients. So we should be good.

**Review by Hyperkid123 — DISMISSED** [review]

**Comment by Hyperkid123** [comment]
@florkbr we are using the convetial commits to update the version during the automated release. Can you change the commit message, please? I think I should turn the commit lint back on.

**Comment by ezr-ondrej** [comment]
@Hyperkid123 can we just squash merge if that's the only thing blocking us? :)

**Comment by Hyperkid123** [comment]
@ezr-ondrej yeah, we can. I just don't like touching other people's work :slightly_smiling_face:. I'll do it.

**Review by Hyperkid123 — APPROVED** [review]

**Comment by ezr-ondrej** [comment]
Amazing, thank you @florkbr and @Hyperkid123 ! :orange_heart:
Looking forward to update my app to new version :tada:

**Comment by Hyperkid123** [comment]
All affected packages are released

**Pull request merged**
